# Generated by Django 5.2.3 on 2025-07-04 19:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_pic.jpeg', null=True, upload_to=api.models.upload_to),
        ),
    ]
